title: Imperial Eyes
author: 
email: arielhahn@ucla.edu / asawilder@gmail.com
description: >-
  a digital humanities project 
baseurl: "/i_e/" # the subpath of your site, e.g. /blog
url: "https://aireuhl.github.io" # your site's origin, e.g. https://forestry.io

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-menus

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
